version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:

  db:
    image: postgres:13.10-alpine
    container_name: db
    env_file: ./.env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/  # OK

  backend:
    container_name: backend
    image: notilttoday1/foodgram_backend
    env_file: ./.env
    volumes:
      - static_foodgram:/backend/collected_static/  # OK
      - media_foodgram:/backend/media/  # OK
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: notilttoday1/foodgram_frontend
    env_file: ./.env
    volumes:
      - ./frontend/:/app/result_build/ # OK
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    env_file: ./.env
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 80(localhost по умолчанию локально) хоста
    # на порт 80 контейнера.
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static/
      - media_static:/var/html/media/
    depends_on:
      - backend
      - frontend
