version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:

  db:
    image: postgres:13.10-alpine
    container_name: db
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/

  backend:
    container_name: backend
    build: ./backend
    env_file: .env
    volumes:
      - static_foodgram:/collected_static
      - media_foodgram:/media
     # - ../backend:/backend   Mount - все файлы созданные внутри контейнера копируются на компьютер.
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: notilttoday1/foodgram_frontend
    env_file: .env
    volumes:
      - static_foodgram:/app/result_build/

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    env_file: ./.env
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 80(localhost по умолчанию локально) хоста
    # на порт 80 контейнера.
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/etc/nginx/html/static/
      - media_foodgram:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend